### ISSUE TITLE
Add Waushara County and the City of Superior Deliveries

### ISSUE THREAD

**Issue by HaydenElza** [WIStCart/lidar-data-inventory#4]
The Waushara County 2017 delivery can be found here:
ftp://ftp.ssec.wisc.edu/pub/wisconsinview/lidar/Waushara/Waushara_2017_FEMA_Delivery/ 
and the City of Superior 2019 delivery can be found here:
ftp://ftp.ssec.wisc.edu/pub/wisconsinview/lidar/Douglas/CityofSuperior_2019_City_Delivery/

**Comment by HaydenElza** [comment]
Commit 0128e60 added the tile indices for these two deliveries, but we still need to add Waushara county info to the _LidarData.csv_. @AnaJWells Could you add that info to the CSV?

**Comment by AnaJWells** [comment]
The Waushara County 2017 and City of Superior 2019 deliveries information is updated in the CSV.

**Comment by HaydenElza** [comment]
It looks like you pushed your commit to the `master` branch. I should have clarified that I was working on branch `issue4`. Reopening to merge `issue4` with `master`.

**Comment by HaydenElza** [comment]
Merged your changes @AnaJWells into the `issue4` branch in commit 5618e10223ee1b83a731cce9a9bc9261dbc7365b then merged branch `issue4` into `master` in commit 06b31186d7abb7837493352fa4d31af092ddb1f1. 

I tested the changes, everything seems to be working so I also updated the sco.wisc.edu production site.

Closing issue.
